### ISSUE TITLE
성능 개선 필요합니다

### ISSUE THREAD

**Issue by donggeunkoh** [cezanne23/deepthinking#53]
현재 10개 TC 수행하는데 4시간 즘 걸리는것으로 파악이 됩니다.

각자 구현하신 부분들 중에서 개선 할만한 포인트가 있다면 편하게 알려주시면 감사드리겠습니다!

**Comment by hs-will-lee** [comment]
EmployeeInfo 에 대한 참조 생성자가 없는 것이 리스트 생성에 문제가 될 수도 있을 것 같네요. 현재 13초 걸리는데 , 생성자 만들어서 확인해 보겠습니다.

**Comment by donggeunkoh** [comment]
오.... 정말 좋은 포인트 같습니다.

**Comment by donggeunkoh** [comment]
저는 함수 파라미터에서 list, map, vector들을 레퍼런스로 입력받고있는지 확인부터 한번 해보겠습니다. 
시간은 크게 차이 안날수도 있을것같습니다 ㅠㅠ

**Comment by cezanne23** [comment]
// 이 부분을 삭제하고 
        for (const auto& employeeNum : list) {
            infoList.push_back(employeeDB->employeeList[employeeNum]);
        }
        // 인자로 전달받은 vector<string> list  : employeeNum 로 sorting 진행 
        priorityQueue.sort(infoList);
      이렇게 하면 push 로직을 줄일 수 있을 것 같습니다.

**Comment by jseong-uu** [comment]
vector의 경우 resize로 인한 overhead도 있다고 들었습니다. reserve가 가능한 부분은 reserve를 해두고 진행해도 좋을 것 같아요.

**Comment by hs-will-lee** [comment]
참조 생성자 반영해서 최대  insert의 경우 13 -> 9.4 초로 줄었습니다.

**Comment by hs-will-lee** [comment]
릴리즈 빌드와 디버그 빌드 사이의 속도차가 심합니다. 릴리즈 모드로 테스트하여야 할 것으로 보입니다. 

<Debug mode>
[----------] 5 tests from SearchEngineMaxDBTest
[----------] 5 tests from SearchEngineMaxDBTest (20107 ms total)

<Release mode>
[ RUN      ] SearchEngineMaxDBTest.MaxDBTest
[----------] 5 tests from SearchEngineMaxDBTest (862 ms total)
